### PR TITLE
Fix Ready Sound

### PR DESCRIPTION
**Pull request by Johnex**

### CODE REVIEW

**Comment by yaapu** [comment]
Hi this is to generate a sound that "complies" with the one I distribute?

**Comment by Johnex** [comment]
You remember a while ago i gave you a way to generate the sounds using TTSAutomate, that specific line the "Yaapu telemetry ready" doesn't sound as intended without the change, it says something like yaap telemetry, not YAA-Pu as it should say :D.

**Comment by yaapu** [comment]
Ok, I'll have to test it myself, looks good though ;-)

**Comment by Johnex** [comment]
The TTSAutomate voice is higher quality than the ones you include too i think. Uses Amazon's TTS.

**Pull request merged**
